#!/usr/bin/env python

import gzip
import logging
import os

import lxml.etree

import eutils.client
import eutils.clientx

# new style
from eutils.xmlfacades.entrezgeneset import EntrezgeneSet

# old style
import eutils.xmlfacades.einfo


logging.basicConfig(level=logging.DEBUG)


data_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)),'..','tests','data')


xml = gzip.open(os.path.join(data_dir,'entrezgeneset.xml.gz')).read()
doc = lxml.etree.XML(xml)
egs = EntrezgeneSet(doc)

print("{} genes in EntrezgeneSet".format(len(egs.entrezgenes)))
for eg in egs:
    print("\t".join(map(str,[eg.gene_id,eg.maploc,eg.hgnc,
                             eg.summary[:30] + "..." if eg.summary else None])))



#ec = eutils.clientx.ClientX()
#gene = ec.fetch_gene_by_hgnc('VHL')
#gc = gene.references[0].products[0].genomic_coords
#gbseq = ec.fetch_gbseq_by_ac(gene.references[0].products[0].acv)

import IPython; IPython.embed()

