#!/usr/bin/env python

import gzip
import logging
import os

import lxml.etree

import eutils.client
import eutils.clientx

# new style
from eutils.xmlfacades.esearchresult import ESearchResult
from eutils.xmlfacades.entrezgeneset import EntrezgeneSet

logging.basicConfig(level=logging.DEBUG)

data_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)),'..','tests','data')


if False:
    xml = gzip.open(os.path.join(data_dir,'esearch.fcgi?term=hart%20rk[author].xml.gz')).read()
    doc = lxml.etree.XML(xml)
    esr = ESearchResult(doc)


if False:
    xml = gzip.open(os.path.join(data_dir,'entrezgeneset.xml.gz')).read()
    doc = lxml.etree.XML(xml)
    egs = EntrezgeneSet(doc)

    print("{} genes in EntrezgeneSet".format(len(egs.entrezgenes)))
    for eg in egs:
        print("\t".join(map(str,[eg.gene_id,eg.maploc,eg.hgnc,
                                eg.summary[:30] + "..." if eg.summary else None])))


if True:
    ec = eutils.client.Client()
    esr = ec.esearch(db='gene',term='tumor necrosis factor')
    egs = ec.efetch(db='gene',id=esr.ids[0])
    eg = egs.entrezgenes[0]
    # eg.locus, eg.maploc, eg.description, eg.type
    # [ str(r) for r in eg.references ]
    # eg.references[0].acv
    # eg.references[0].products[0].acv
    # eg.references[0].products[0].genomic_coords.strand
    # eg.references[0].products[0].genomic_coords.intervals


import IPython; IPython.embed()

